=== amullins83/BESTField/TestBestCommunicator/Resources/FieldState.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://bestinc.org/xml/schema/field-state" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="DATA">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="TIEBREAK">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="YELLOW" type="xs:unsignedByte" />
              <xs:element name="RED" type="xs:unsignedByte" />
              <xs:element name="BLUE" type="xs:unsignedByte" />
              <xs:element name="GREEN" type="xs:unsignedByte" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="SWSTATUS">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="YELLOW" type="xs:unsignedByte" />
              <xs:element name="RED" type="xs:unsignedByte" />
              <xs:element name="BLUE" type="xs:unsignedByte" />
              <xs:element name="GREEN" type="xs:unsignedByte" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="DEVSTATUS">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="CONFIG" type="xs:unsignedByte" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== amullins83/BESTField/TestBestCommunicator/Resources/FieldStateValid.xml
<?xml version="1.0" encoding="utf-8"?> 
<DATA xmlns="http://bestinc.org/xml/schema/field-state"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://bestinc.org/xml/schema/field-state FieldState.xsd" >
  <TIEBREAK>
	  <YELLOW>4</YELLOW>
	  <RED>4</RED>
	  <BLUE>1</BLUE>
	  <GREEN>2</GREEN>
  </TIEBREAK>
  <SWSTATUS>
	  <YELLOW>0</YELLOW>
	  <RED>0</RED>
	  <BLUE>1</BLUE>
	  <GREEN>1</GREEN>
  </SWSTATUS>
  <DEVSTATUS>
	  <CONFIG>1</CONFIG>
  </DEVSTATUS>
</DATA>
